### PR TITLE
Correct CloudSploit

### PR DESCRIPTION
**Pull request by citizenjosh**

### CODE REVIEW

**Comment by exitcode0** [comment]
checking https://cloudsploit.com/features 
It seems that SSO is only offered on "CloudSploit Enterprise" where as this doesn't seem to be offered on the cheaper "CloudSploit Standard" tier
the prices here might be wrong as the entry hasn't been updated for ~2 years 
but it seems like this vendor is charging more for sso

**Comment by citizenjosh** [comment]
But Enterprise has many other benefits over Free. SSO is one of many included features.

**Comment by majormoses** [comment]
> But Enterprise has many other benefits over Free. SSO is one of many included features.

Then IMHO you have missed the point :wink: the point is to highlight vendors that bundle basic security requirements that any org using more than 5 users should have and saying you need to pay the blood money of an enterprise.

**Comment by Wild1145** [comment]
Pricing now seems to re-direct to https://www.aquasec.com/products/cspm/ which isn't very helpful given it doesn't have any pricing on it... Is anyone able to sign post the new pricing page? What's in the PR doesn't appear to actually take you to a pricing / comparisons table...

**Comment by majormoses** [comment]
They were bought by Aquasec so I assume this is a transitory issue and hope they will eventually have a link to their new pricing.

**Comment by citizenjosh** [comment]
Since opening this PR there have been website changes, including redirects.
The new pricing is available at https://www.aquasec.com/pricing/

**Comment by majormoses** [comment]
Thanks Josh, so it looks like its now available at enterprise for $2,099 a month? Looks like its also no longer per account at that level but looks at the number of resources within the accounts.

**Comment by robchahin** [comment]
Merging this as a rework that drops Cloudsploit and adds the info for Aqua instead

**Pull request merged**
