### PR TITLE
postman raised their SSO prices

### PR DESCRIPTION
**Pull request by deltamualpha**
from $24 to $49 per user/month (billed annually, of course).

### CODE REVIEW

**Comment by rvanlaak** [comment]
When checking the pricing from Amsterdam, the professional plan seems to be $29 / user / month (annually).

image

**Comment by robchahin** [comment]
There's no SAML in the Pro plan, though. I assume the $49 in this PR was supposed to reflect an Enterprise price?

**Comment by deltamualpha** [comment]
Exactly. Pro merely gets you "Google Workspaces" authentication. You have to go all the way to enterprise to get the rest of the SSO buffet (scroll down the page for the full feature breakout).

**Comment by rvanlaak** [comment]
Ok check! Yes the difference between SAML and Workspaces is the part that got me confused here.

**Pull request merged**
