### PR TITLE
Move vendors to data file

### PR DESCRIPTION
**Pull request by GICodeWarrior**
Separates the data from the presentation.

### CODE REVIEW

**Comment by robchahin** [comment]
I like it, but can't merge as-is because it lacks support for multiple sources and footnotes, which are both present.

**Comment by robchahin** [comment]
Actually, given that footnotes can appear in any cell, inline footnotes in the yaml might work and are probably the best solution. Still needs multiple source support though.

**Comment by GICodeWarrior** [comment]
It has support for both already.  Give it a try.

**Comment by robchahin** [comment]
Ah yep, I see it. I'm not familiar with these loops, but it's great.

**Pull request merged**
