### PR TITLE
Add Kandji

### PR DESCRIPTION
**Pull request by opragel**
Adds https://kandji.io to the list. Thanks for this project!

### CODE REVIEW

**Comment by randomrouleur** [comment]
It's $150/month to add SSO for all tiers below the $1,999/month (500 device) tier...
https://www.kandji.io/pricing

**Review by reinstej-sci — APPROVED** [review]
Details are current and correct as of 3/11/21. SSO is included once you hit 401+ devices.

Screen Shot 2021-03-11 at 1 23 22 PM

**Comment by opragel** [comment]
Thanks @reinstej-sci! Let me know if there's anything else I can provide to help get this merged.

**Comment by opragel** [comment]
@robchahin @reinstej-sci Howdy all - anything I can do to help get this merged? Would love to see this project continue!

**Pull request closed without merging**
