### PR TITLE
Add Docker Hub to vendors.yml

### PR DESCRIPTION
**Pull request by NovaAtWarren**
Adds docker hub to list, since they just added a "business" pricing model with SSO

### CODE REVIEW

**Comment by NovaAtWarren** [comment]
Should you want me to put the base price to "Pro" rather than the free "Personal" tier, please let me know.

**Comment by raghuchinnannan** [comment]
I think the base pricing should be pro not the free plan.

**Comment by NovaAtWarren** [comment]
> I think the base pricing should be pro not the free plan.

Done c:

**Review by kengeman — APPROVED** [review]

**Comment by lcycon** [comment]
Fixed in #273

**Pull request closed without merging**
