### PR TITLE
Create teamviewer.yaml

### PR DESCRIPTION
**Pull request by zypA13510**
Closes #38

### CODE REVIEW

**Comment by MMore** [comment]
Again, thanks for your contribution @zypA13510. Added to ssotax.org.

**Comment by zypA13510** [comment]
@MMore Actually, the SSO price for both TeamViewer and AnyDesk is not publicly available ("contact us for quote"). The price I put there is the highest tier without SSO.
I do have a quote from them in private though I may not be able to disclose them. It's much higher than even the highest tier (of course).

**Comment by MMore** [comment]
Hey @zypA13510 , thanks for letting me know. I removed the price. Feel free to adjust whenever you want to add a more exact price tag to it.

**Review by techdarko — APPROVED** [review]
Thanks @zypA13510!

**Pull request merged**
