### PR TITLE
Adding sonatype to the wall

### PR DESCRIPTION
**Pull request by karthich**
Just discovered this today while trying to roll out a SSO solution for our local nexus repo.

### CODE REVIEW

**Comment by robchahin** [comment]
Baed on the $120 pricing in the PR, this might not be eligible. I've excluded entries if SSO is added in the first tier above a free tier, with the rationale that selling business software assumes that you're charging your users.

**Comment by karthich** [comment]
So they're bundling SSO with their other premium features because they think that companies that will need SSO but not the other premium products will still need to pay for premium. How is that not an SSO tax?

By that definition, why is slack in this list? They don't up-charge users for just getting SSO as a feature. Their premium tier has additional perks like 99.9% uptime SLA and "Corporate exports for all messages".
https://share.getcloudapp.com/L1up5gvy

**Comment by Wild1145** [comment]
Is there anywhere that actually states what plans they offer SSO on? The link in the change doesn't show you that...

**Comment by Mansarde** [comment]
> Is there anywhere that actually states what plans they offer SSO on? The link in the change doesn't show you that...

https://help.sonatype.com/repomanager3/system-configuration/user-authentication/saml
On that page it says: "Available in Nexus Repository Manager Pro only"

**Comment by robchahin** [comment]
Revisiting, I think the previous discussion is still true. They have a free tier and a paid tier, and SSO is only available in the paid tier. This contrasts with Slack (per earlier question) because Slack has a paid tier, and a paid tier with SSO that's more expensive.

My view of this is effectively that Sonatype offers a single license, which includes SSO, and it has a free tier available if you don't care too much about which features you get. The "free tier is excluded" policy isn't perfect but it works most of the time.

**Pull request closed without merging**
